spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: sharding-encrypt
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    dataSources:
      db0:
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://114.132.79.213:3306/sharding_db0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
        username: sharding
        password: sharding321!
      db1:
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://114.132.79.213:3306/sharding_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
        username: sharding
        password: sharding321!
    rules:
      #  定义加密规则
      encrypt:
        tables:
          t_user:
            columns:
              user_name:
                cipher:
                  name: user_name
                  encryptorName: none
                likeQuery:
                  # 加密字段
                  name: user_name_like_query
                  # 加密使用规则
                  encryptorName: char_digest_like
              # 配置密码的加密规则
              pwd:
                # 设置原字段不加密
                cipher:
                  name: pwd
                  encryptorName: none
                # 设置辅助查询字段的值为MD5加密以后的值
                assistedQuery:
                  name: pwd_cipher
                  encryptorName: assisted_encryptor
        encryptors:
          # 空加密算法
          none:
            type: NONE
          # 自定义MD5加盐加密算法
          md5_myself:
            type: MD5NEW
            props:
              slat: 123456abc
          # AES加密算法
          aes_encryptor:
            type: AES
            props:
              aes-key-value: 123456abc
          # MD5加密算法
          assisted_encryptor:
            type: MD5
          # 模糊匹配加密算法
          char_digest_like:
            type: CHAR_DIGEST_LIKE
      sharding:
        # 分片规则配置
        shardingAlgorithms:
          user_table_complex:
            type: INLINE
            props:
              algorithm-expression: t_user${user_id % 4}
          user_db_complex:
            type: INLINE
            props:
              algorithm-expression: db${user_id % 2}
        tables:
          # 配置t_user表的分片规则
          t_user:
            actualDataNodes: db${0..1}.t_user${0..3}
            tableStrategy:
              standard:
                shardingColumn: user_id
                shardingAlgorithmName: user_table_complex
            databaseStrategy:
              standard:
                shardingColumn: user_id
                shardingAlgorithmName: user_db_complex
            # 配置user_id使用雪花算法生产
            keyGenerateStrategy:
              column: user_id
              keyGeneratorName: snowflake
            # 配置审计算法
            auditStrategy:
              auditorNames:
                - sharding_key_required_auditor
        keyGenerators:
          # 配置雪花算法
          snowflake:
            type: SNOWFLAKE
        auditors:
          # 配置审计算法
          sharding_key_required_auditor:
            type: DML_SHARDING_CONDITIONS
    props:
      # SQL语句打印
      sql-show: true
      # 简化打印SQL语句
      sql-simple: false
      # 禁用执行SQL用于获取数据库元数据
      check-table-metadata-enabled: true

server:
  port: 8003

logging:
  config: classpath:logConfig/logback-dev.xml
  level:
    root: INFO
    com:
      github:
        lazyboyl:
          shardingsphere: DEBUG

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
